#define ENUM(E) StaticValue(#E, Napi::Number::New(env, E))

// egrep '^\s+SRTO' srtcore/srt.h | sed 's/^.*\(SRTO_[^, ]*\)[, ].*$/  ENUM\(\1\), \\/'

#define SOCKET_OPTIONS \
  ENUM(SRTO_MSS), \
  ENUM(SRTO_SNDSYN), \
  ENUM(SRTO_RCVSYN), \
  ENUM(SRTO_ISN), \
  ENUM(SRTO_FC), \
  ENUM(SRTO_SNDBUF), \
  ENUM(SRTO_RCVBUF), \
  ENUM(SRTO_LINGER), \
  ENUM(SRTO_UDP_SNDBUF), \
  ENUM(SRTO_UDP_RCVBUF), \
  ENUM(SRTO_RENDEZVOUS), \
  ENUM(SRTO_SNDTIMEO), \
  ENUM(SRTO_RCVTIMEO), \
  ENUM(SRTO_REUSEADDR), \
  ENUM(SRTO_MAXBW), \
  ENUM(SRTO_STATE), \
  ENUM(SRTO_EVENT), \
  ENUM(SRTO_SNDDATA), \
  ENUM(SRTO_RCVDATA), \
  ENUM(SRTO_SENDER), \
  ENUM(SRTO_TSBPDMODE), \
  ENUM(SRTO_INPUTBW), \
  ENUM(SRTO_OHEADBW), \
  ENUM(SRTO_PASSPHRASE), \
  ENUM(SRTO_STREAMID), \
  ENUM(SRTO_PBKEYLEN), \
  ENUM(SRTO_KMSTATE), \
  ENUM(SRTO_IPTTL), \
  ENUM(SRTO_IPTOS), \
  ENUM(SRTO_TLPKTDROP), \
  ENUM(SRTO_SNDDROPDELAY), \
  ENUM(SRTO_NAKREPORT), \
  ENUM(SRTO_VERSION), \
  ENUM(SRTO_PEERVERSION), \
  ENUM(SRTO_CONNTIMEO), \
  ENUM(SRTO_SNDKMSTATE), \
  ENUM(SRTO_RCVKMSTATE), \
  ENUM(SRTO_LOSSMAXTTL), \
  ENUM(SRTO_RCVLATENCY), \
  ENUM(SRTO_PEERLATENCY), \
  ENUM(SRTO_MINVERSION), \
  ENUM(SRTO_STREAMID), \
  ENUM(SRTO_CONGESTION), \
  ENUM(SRTO_MESSAGEAPI), \
  ENUM(SRTO_PAYLOADSIZE), \
  ENUM(SRTO_TRANSTYPE), \
  ENUM(SRTO_KMREFRESHRATE), \
  ENUM(SRTO_KMPREANNOUNCE), \
  ENUM(SRTO_ENFORCEDENCRYPTION), \
  ENUM(SRTO_IPV6ONLY), \
  ENUM(SRTO_PEERIDLETIMEO), \
  ENUM(SRTO_PACKETFILTER)
  
#define SOCKET_STATUS \
  ENUM(SRTS_INIT), \
  ENUM(SRTS_OPENED), \
  ENUM(SRTS_LISTENING), \
  ENUM(SRTS_CONNECTING), \
  ENUM(SRTS_CONNECTED), \
  ENUM(SRTS_BROKEN), \
  ENUM(SRTS_CLOSING), \
  ENUM(SRTS_CLOSED)
